name: xpns42
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  file: ^6.1.4
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_database: ^10.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.0.0
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  go_router: ^8.0.2
  http: ^0.13.5
  intl: any
  json_annotation: ^4.8.1
  path: ^1.8.2
  pocketbase: ^0.10.1
  pointycastle: ^3.7.3
  riverpod_annotation: ^1.2.1
  shared_preferences: ^2.0.18
  #sqflite: ^2.2.5
  #sqflite_common_ffi: ^2.2.1+1

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^1.1.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Percolator
      fonts:
        - asset: assets/fonts/Percolator/percolator-expert.ttf
    - family: WoD3
      fonts:
        - asset: assets/fonts/WoD3/WOD3____.ttf
    - family: Cardo
      fonts:
        - asset: assets/fonts/Cardo/Cardo-Regular.ttf
        - asset: assets/fonts/Cardo/Cardo-Italic.ttf
          style: italic
        - asset: assets/fonts/Cardo/Cardo-Bold.ttf
          weight: 700

flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon/saco.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/launcher_icon/saco.png"
  color_dark: "#434343"
  image_dark: "assets/launcher_icon/saco.png"
  android: true
  ios: true
