name: xpns42
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_database: ^10.2.4
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.2.0
  google_fonts: ^6.1.0
  intl: any
  json_annotation: ^4.8.1
  nanoid: ^1.0.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.0.15
  pointycastle: ^3.7.3
  purchases_flutter: ^6.4.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf  
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf  
          weight: 400
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

flutter_launcher_icons:
  remove_alpha_ios: true
  image_path: "assets/img/logo.png"
  ios: true
  android: true
  macos:
    generate: true
    image_path: "assets/img/logo.png"
    
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/img/splash.jpg"
  color_dark: "#FFFFFF"
  image_dark: "assets/img/splash.jpg"
  android: true
  ios: true
