name: xpns42
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+48

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.3
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  nanoid: ^1.0.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.2
  pocketbase: ^0.18.0
  pointycastle: ^3.7.4
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.3
  wolt_modal_sheet: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  remove_alpha_ios: true
  image_path: "assets/img/logo.png"
  ios: true
  android: true
  macos:
    generate: true
    image_path: "assets/img/logo.png"
    
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/img/splash.jpg"
  color_dark: "#FFFFFF"
  image_dark: "assets/img/splash.jpg"
  android: true
  ios: true
