name: xpns42
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gettext_i18n: ^1.0.5
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon/saco.png"
